apiVersion: batch/v1
kind: Job
metadata:
  name: capstone-migration-runner-003
  namespace: capstone
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: migration-runner
          image: capstone-api:v3
          imagePullPolicy: Never

          command:
            - node
            - src/migrate.js

          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-credentials

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL