replicaCount: 2

image:
  repository: capstone-api
  tag: v2
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi